export const appActionTypes = {
	UPDATE_SEARCH_PARAMS: 'UPDATE_APP_SEARCH_PARAMS',
	TOGGLE_ADVANCE_SEARCH: 'TOGGLE_ADVANCE_SEARCH',
	UPDATE_SEARCH_RESULTS: 'UPDATE_SEARCH_RESULTS',
	REMOVE_SEARCH: 'REMOVE_SEARCH',
	UPDATE_ERROR_MESSAGE: 'UPDATE_ERROR_MESSAGE',
	REMOVE_ERROR_MESSAGE: 'REMOVE_ERROR_MESSAGE',
	UPDATE_SUCCESS_MESSAGE: 'UPDATE_SUCCESS_MESSAGE',
	REMOVE_SUCCESS_MESSAGE: 'REMOVE_SUCCESS_MESSAGE',
	ADD_DATA: 'ADD_DATA',
	REMOVE_DATA: 'REMOVE_DATA',
	UPDATE_PAGENUMBER_SEARCH_PARAM: 'UPDATE_PAGE_NUMBER_SEARCH_PARAM'
}
